name: Staging Deployment

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Build Staging Assets
      run: npm run build:staging
      env:
        VITE_APP_ENV: staging
        VITE_API_BASE_URL: https://api.staging.iqube.network
    
    - name: Deploy to Staging Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_SERVER_HOST }}
        username: ${{ secrets.STAGING_SERVER_USER }}
        key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/staging.iqube.network
          git pull origin staging
          npm install
          npm run build:staging
          pm2 restart staging-app
